### ISSUE TITLE
Postfix 3.9 released

### ISSUE THREAD

**Issue by Player701** [eilandert/deb.myguard.nl#13] opened 2024-10-06 15:49 UTC
Greetings from a long-time user of your repository. It seems that the latest version of Postfix available there is only 3.8.4, while the actual latest version as of now is 3.9.0, released more than half a year ago. Seeing as the changelog appears to contain a few security-related improvements, it'd be really nice if you updated to the packages to 3.9.0 to keep up with the official release.

Thank you very much.

**Comment by eilandert** [comment] 2024-10-21 23:00
It seems there is some kind of conflict I need to resolve, some distributions want PCRE3 and some want PCRE2, I might need to seperate packages or abandon "old" distro's.

**Comment by schories** [comment] 2024-10-22 08:14
On https://deb.myguard.nl/ you state:


_"Debian Trixie and Bookworm and when it builds Bullseye and Buster"_

IMHO: Buster is completely EOL since months now. Bullseye is in LTS maintenance since August.

=> Please consider dropping Buster. Keep Bullseye as long as it's manageable with low effort.


_"Ubuntu Noble and Jammy and when it builds Focal and Bionic"_

https://ubuntu.com/about/release-cycle


IMHO: I'd kindly suggest to focus on LTS times only - as I simply can't fathom 12 year "legacy" support, for all of these, by you and some supporters only.. ;-) 

=> Thus please also consider dropping Bionic. Keep Focal as long as it's manageable with low effort.


Overall, it is far better to focus on and service a current repo than to waste time and effort on those who must run in the past.  There are commercial services for these use cases - for a reason.

**Comment by schories** [comment] 2024-10-22 08:30
That being said, I would have a look into this. (_"You can download the source-deb, unpack it, fix things, add things, make a diff and send it to me"_).

I apologize, but 
- I haven't exactly found source debs, e.g. in https://deb.myguard.nl/pool/main/p/postfix/ there are *.orig.tar.gz - but not source debs with your patches/config/build-parameters.
- once the decision regarding supported releases is made by you, I'd prepare a building/testing environment

Thank you once again!

**Comment by eilandert** [comment] 2024-10-22 12:22
> That being said, I would have a look into this. (_"You can download the source-deb, unpack it, fix things, add things, make a diff and send it to me"_).
> 
> I apologize, but
> 
>     * I haven't exactly found source debs, e.g. in https://deb.myguard.nl/pool/main/p/postfix/ there are *.orig.tar.gz - but not source debs with your patches/config/build-parameters.
> 
>     * once the decision regarding supported releases is made by you, I'd prepare a building/testing environment
> 
> 
> Thank you once again!

Yes, Buster is out, Bionic too.  I have disabled them in some packages already when the build fails.

there is also a .debian.tar.xz, it contains the /debian directory with everything in it.
if you put that in an extracted (updated) postfix.tar.gz you can use debuild to build it.  (or use debocker, it might be easier to test a build for multiple distro's). I use pbuilder and my own scripts to make release builds.

The problem was, as far as I can remember, the Trixie build compiled, but then the Bullseye won't, and vice versa
I don't know the details anymore, maybe it's a quick fix, maybe not.

**Comment by schories** [comment] 2024-10-22 14:12
Great. 

- To keep your build scripts/env super-confidential I'd prepare an [OBS](https://openbuildservice.org/) based solution which I'd document and release. Overall goal: Automate creation of packages like you did. So I can catch build fails, too - before manually an issue will be opened. And - most importantly - to enjoy automated builds anytime an upstream package is updated. :grin:
- Maybe even look into [reproducible builds](https://reproducible-builds.org/tools/) some time later.

What's your take on this, Thijs?

@all Feedback & advice are highly appreciated.

**Comment by eilandert** [comment] 2024-10-23 22:15
@schories I've sent you a mail.  I'll close this issue because postfix is fixed :)

**Closed by eilandert** 2024-10-23 22:15 UTC

**Comment by Player701** [comment] 2024-10-24 07:19
@eilandert and co. - thank you very much for resolving this! I will report back if anything breaks.
